export {default as Header} from './header'
export {default as Footer} from './footer'
export {default as Home} from './home'
export {default as About} from './about'
export {default as UXDesign} from './uxdesign'
export {default as WebDevelopment} from './webdev'
export {default as WebsiteDesign} from './website'
